version: '3.7'

services:
    idp:
        container_name: idp
        image: ghcr.io/identicum/keycloak:22.0
        restart: always
        environment:
            KEYCLOAK_ADMIN: admin
            KEYCLOAK_ADMIN_PASSWORD: admin
        volumes:
            - ./keycloak/:/opt/keycloak/data/import/
        command: "start-dev --import-realm"
        ports:
            - 8080:8080
    demoapp:
        container_name: demoapp
        image: ghcr.io/identicum/oidc-demoapp-spring:latest
        restart: always
        ports:
            - 8081:8080
        environment:
            OIDC_BASE_URL: http://idp:8080/realms/demorealm
            OIDC_CLIENT_ID: demoapp_client_id
            OIDC_CLIENT_SECRET: demoapp_client_secret
        depends_on:
            idp:
                condition: service_healthy
